### ISSUE TITLE
init_indy_node.py and create_pool_ledger_genesis_file.py issue

### ISSUE THREAD

**Issue by gruming** [Ta-SeenJunaid/Hyperledger-Indy-Tutorial#1]
Hello.

Thanks for sharing the good tutorial code.

With your code I created the pool_ledger_genesis_file and I ran into a problem.

I initially configured the node using init_indy_node.py, but the BLS value was 175 characters.
And there was a problem in the process of creating connection information for each node using create_pool_ledger_genesis_file.py.
So, I modified the line of code below and executed it.

https://github.com/Ta-SeenJunaid/Hyperledger-Indy-Tutorial/blob/ab78bd5c09472cc51ea1ecab2d153680f15d6ad0/indy_network/create_pool_ledger_genesis_file.py#L65

An issue was created in this way to convey that there are cases where the BLS value is 174 or higher when the node is initially configured using init_indy_node.py.

Thanks again for sharing a good tutorial :)

p.s: The readability is not very good because the issue is registered using Google Translate.

**Comment by Ta-SeenJunaid** [comment]
Dear SooMin Jeong,

Thank you for your support. I'll try to fix the issue ASAP.
