### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by guilherme-funchal** [Ta-SeenJunaid/Hyperledger-Indy-Tutorial#2]
Thank you for sharing your knowledge. How could I generate new Blskey and BlsProofs values ​​for new seeds?

**Comment by Ta-SeenJunaid** [comment]
The code for  new Blskey and BlsProofs values ​​for new seeds are written on "init_indy_node.py" file. You can find the required output if you execute this command: "sudo python3 init_indy_node.py \
--name Node1 --seed 4000F000u00000D0000000g0000Node1" .
Place your custom seed value into that command after "--seed" flag.

More details can be found on:
https://medium.com/@taseen.junaid/hyperledger-indy-custom-network-with-indy-node-plenum-protocol-ledger-85fd10eb5bf5

**Comment by guilherme-funchal** [comment]
Ok, thanks. 

Do I need to generate new Steward and Trustee(BLSKeys e BLSProof) identifiers if I decide to change?

**Comment by guilherme-funchal** [comment]
Hi, thanks, it's works.

Would you know how to add the new node to the pool in indy-cli?

**Comment by Ta-SeenJunaid** [comment]
You can follow this link with some modification.

https://hyperledger-indy.readthedocs.io/projects/node/en/latest/add-node.html

**Comment by guilherme-funchal** [comment]
Thanks

To work I did this:

<pre>
#pool create serpro gen_txn_file=/home/indy/ledger/serpro/pool_transaçãos_genesis
#wallet create test_wallet key=password
#pool connect test
#wallet open test-wallet key=password
#did new seed=000000000000000000000000Steward4
#did new seed=000000000000000000000000Trustee1

//Use DID of Trustee1
#did use V4SGRU86Z58d6TV7PBUe6f
#ledger nym did=TWwCRQRZ2ZHMJFn9TzLp7W verkey=~UhP7K35SAXbix1kCQV4Upx role=STEWARD

//Use DID of Steward4
#did use TWwCRQRZ2ZHMJFn9TzLp7W
#did use TWwCRQRZ2ZHMJFn9TzLp7W

//Add new node4
#ledger node target=4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA node_ip=192.168.2.7 node_port=9707 client_ip=192.168.2.7 client_port=9708 alias=Node4 serviços=VALIDATOR blskey=2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw blskey_pop=RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP

</pre>
