### ISSUE TITLE
error with prerequisites.sh

### ISSUE THREAD

**Issue by tfoutrein** [Ta-SeenJunaid/Hyperledger-Indy-Tutorial#4]
When trying to install Prerequisites, i have the following error 

```
The following packages have unmet dependencies:
 indy-plenum : Depends: python3-orderedset (= 2.0) but 2.0.3 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-pympler (= 0.5) but 0.8 is to be installed
E: Unable to correct problems, you have held broken packages.
```
do you have a solution ?

Thanks in advance

Thomas

**Comment by tfoutrein** [comment]
i found the solution replace line 25 in prerequisite.sh by : 

```
sudo apt-get update -y && sudo apt-get install -y \
indy-node=1.13.0~dev1213 libindy-crypto=0.4.5 python3-indy-crypto=0.4.5 python3-orderedset=2.0 python3-psutil=5.4.3 python3-pympler=0.5 indy-plenum=1.13.0~dev1021 libindy=1.15.0~1536-xenial indy-cli=1.15.0~1536-xenial
```

**Comment by Ta-SeenJunaid** [comment]
> i found the solution replace line 25 in prerequisite.sh by :
> 
> ```
> sudo apt-get update -y && sudo apt-get install -y \
> indy-node=1.13.0~dev1213 libindy-crypto=0.4.5 python3-indy-crypto=0.4.5 python3-orderedset=2.0 python3-psutil=5.4.3 python3-pympler=0.5 indy-plenum=1.13.0~dev1021 libindy=1.15.0~1536-xenial indy-cli=1.15.0~1536-xenial
> ```

Thank you very much for the solution. Actually I'm a bit busy with my education and so failed to give any solution. Thanks a lot for the solution.
